# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tauri Build & (Optional) Steam Upload

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [macos-14, ubuntu-22.04, windows-2022]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: dtolnay/rust-toolchain@stable

      - name: Linux deps
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install Tauri CLI
        run: npm i -D @tauri-apps/cli

      # ---- Build web (portable) and sync to app/ ----
      - name: Build web (if needed) and sync to app/
        run: |
          set -euo pipefail
          SRC="vendor/sixarata"

          # Build if script exists
          if [ -f "$SRC/package.json" ] && npm --prefix "$SRC" run | grep -qE '(^|[[:space:]])build([[:space:]]|:)'; then
            npm --prefix "$SRC" ci
            npm --prefix "$SRC" run build
          fi

          # Find index.html in common locations
          CANDIDATES=("$SRC/dist" "$SRC/build" "$SRC/out" "$SRC/public" "$SRC")
          FOUND=""
          for C in "${CANDIDATES[@]}"; do
            if [ -f "$C/index.html" ]; then FOUND="$C"; break; fi
          done
          if [ -z "$FOUND" ]; then
            echo "::group::Candidate listings"
            for C in "${CANDIDATES[@]}"; do
              echo "== $C"; ls -la "$C" 2>/dev/null | sed -n '1,120p' || true
            done
            echo "::endgroup::"
            echo "::error::No index.html found in any candidate directory."
            exit 1
          fi

          # Copy to app/ (portable copy)
          rm -rf app && mkdir -p app
          shopt -s dotglob nullglob
          cp -R "$FOUND"/* app/ || true
          # Remove junk
          rm -rf app/.git app/.github app/node_modules app/src-tauri

          # Guards
          if [ ! -f app/index.html ]; then echo "::error::app/index.html missing after sync"; exit 1; fi
          cnt=$(find app -type f | wc -l | tr -d ' ')
          if [ "$cnt" -lt 3 ]; then echo "::error::app/ has too few files ($cnt)"; exit 1; fi
          if ! grep -q '"frontendDist": "../app"' src-tauri/tauri.conf.json; then
            echo "::warning::Set \"frontendDist\": \"../app\" in src-tauri/tauri.conf.json"
          fi

      - name: Tauri info
        run: npx tauri info

      - name: Tauri build (verbose)
        run: |
          set -euo pipefail
          npx tauri build --verbose 2>&1 | tee tauri-build.log

      # ---- Collect artifacts deterministically (no fragile globs) ----
      - name: Collect macOS bundles (Bash 3.2 compatible)
        if: ${{ matrix.os == 'macos-14' }}
        run: |
          set -euo pipefail
          mkdir -p _collect/macos
          found=0
      
          # Copy any .app bundles
          while IFS= read -r -d '' f; do
            echo "Copy $f"
            cp -R "$f" "_collect/macos/"
            found=1
          done < <(find src-tauri/target -type d -name '*.app' -print0 2>/dev/null)
      
          # Copy any .dmg images
          while IFS= read -r -d '' f; do
            echo "Copy $f"
            cp -R "$f" "_collect/macos/"
            found=1
          done < <(find src-tauri/target -type f -name '*.dmg' -print0 2>/dev/null)
      
          if [ "$found" -eq 0 ]; then
            echo "::group::Build log (tail)"; tail -n 2000 tauri-build.log || true; echo "::endgroup::"
            echo "::group::Target tree"; find src-tauri/target -maxdepth 5 -print; echo "::endgroup::"
            echo "::error::No macOS bundles (.app/.dmg) found."
            exit 1
          fi

          ls -la _collect/macos

      - name: Upload macOS bundle(s)
        if: ${{ matrix.os == 'macos-14' }}
        uses: actions/upload-artifact@v4
        with:
          name: bundle-macos-14
          path: _collect/macos/**
          if-no-files-found: error

      - name: Collect Windows bundles (exe/msi) — Bash compatible
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          set -euo pipefail
          mkdir -p _collect/windows
          found=0
      
          while IFS= read -r -d '' f; do
            echo "Copy $f"
            cp -R "$f" "_collect/windows/"
            found=1
          done < <(find src-tauri/target -type f \( -name '*.exe' -o -name '*.msi' \) -print0 2>/dev/null)
      
          if [ "$found" -eq 0 ]; then
            echo "::group::Build log (tail)"; tail -n 2000 tauri-build.log || true; echo "::endgroup::"
            echo "::group::Target tree"; find src-tauri/target -maxdepth 5 -print; echo "::endgroup::"
            echo "::error::No Windows bundles (.exe/.msi) found."
            exit 1
          fi
      
          ls -la _collect/windows

      - name: Upload Windows bundle(s)
        if: ${{ matrix.os == 'windows-2022' }}
        uses: actions/upload-artifact@v4
        with:
          name: bundle-windows-2022
          path: _collect/windows/**
          if-no-files-found: error

      - name: Collect Linux bundles (AppImage/deb/rpm) — Bash compatible
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          set -euo pipefail
          mkdir -p _collect/linux
          found=0
      
          while IFS= read -r -d '' f; do
            echo "Copy $f"
            cp -R "$f" "_collect/linux/"
            found=1
          done < <(find src-tauri/target -type f \( -name '*.AppImage' -o -name '*.deb' -o -name '*.rpm' \) -print0 2>/dev/null)
      
          if [ "$found" -eq 0 ]; then
            echo "::group::Build log (tail)"; tail -n 2000 tauri-build.log || true; echo "::endgroup::"
            echo "::group::Target tree"; find src-tauri/target -maxdepth 5 -print; echo "::endgroup::"
            echo "::error::No Linux bundles (AppImage/deb/rpm) found."
            exit 1
          fi
      
          ls -la _collect/linux

      - name: Upload Linux bundle(s)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v4
        with:
          name: bundle-ubuntu-22.04
          path: _collect/linux/**
          if-no-files-found: error

  steam:
    name: Prepare Steam folders & (optional) upload
    needs: build
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    env:
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Expand artifacts into workspace layout
        run: |
          set -euo pipefail
          mkdir -p src-tauri/target/release/bundle
          # macOS
          if ls artifacts/bundle-macos-14 1>/dev/null 2>&1; then
            mkdir -p src-tauri/target/release/bundle/macos
            cp -R artifacts/bundle-macos-14/* src-tauri/target/release/bundle/macos/ || true
          fi
          # Windows
          if ls artifacts/bundle-windows-2022 1>/dev/null 2>&1; then
            mkdir -p src-tauri/target/release/bundle/nsis src-tauri/target/release/bundle/msi
            cp -R artifacts/bundle-windows-2022/* src-tauri/target/release/bundle/ -v || true
          fi
          # Linux
          if ls artifacts/bundle-ubuntu-22.04 1>/dev/null 2>&1; then
            mkdir -p src-tauri/target/release/bundle/appimage src-tauri/target/release/bundle/deb src-tauri/target/release/bundle/rpm
            cp -R artifacts/bundle-ubuntu-22.04/* src-tauri/target/release/bundle/ -v || true
          fi

      - name: Install helpers
        run: sudo apt-get update && sudo apt-get install -y bash coreutils findutils p7zip-full

      - name: Gather macOS
        run: bash steam/scripts/gather_macos.sh

      - name: Gather Linux
        run: bash steam/scripts/gather_linux.sh

      - name: Gather Windows
        shell: pwsh   # only this one needs PowerShell
        run: ./steam/scripts/gather_win.ps1

      - name: Upload Steam-ready folders as artifact
        uses: actions/upload-artifact@v4
        with:
          name: steam-release-folders
          path: |
            release/osx/Sixarata/**
            release/linux/Sixarata/**
            release/win64/Sixarata/**

      - name: Upload to Steam (steamcmd in Docker)
        run: |
          docker run --rm -v "$PWD:/work" -w /work cm2network/steamcmd \
            bash -lc \
            "/home/steam/steamcmd/steamcmd.sh +login \"$STEAM_USERNAME\" \"$STEAM_PASSWORD\" +run_app_build steam/build_app.vdf +quit"
